[package]
name = "hunting"
version = "0.1.0"
authors = ["Hermes Zhang <chenhuiz@axis.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
bevy_rapier2d = "0.9.0"
rand = "0.8.3"
